In [2]:
import numpy as np 
import pandas as pd 

In [2]:
pd.__version__

'2.3.1'

In [3]:
car_table = pd.read_csv("/workspaces/ml_zoomcamp/week_1/car_fuel_efficiency.csv")
car_table.head(1)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   

   acceleration  model_year  origin fuel_type       drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline  All-wheel drive        0.0   

   fuel_efficiency_mpg  
0            13.231729

In [15]:
car_table.shape

(9704, 11)

In [18]:
car_table["fuel_type"].nunique()

2

In [28]:
null_columns = car_table.isnull().any().sum()
null_columns

np.int64(4)

In [32]:
max_efficincy = car_table.loc[car_table["origin"] == "Asia", "fuel_efficiency_mpg"].max()
max_efficincy

np.float64(23.759122836520497)

In [4]:
median_horsepower = car_table["horsepower"].median()
frequent_horsepower = car_table["horsepower"].mode().iloc[0]
print(f"the median horsepower: {median_horsepower}")
print(f"the most frequent horsepower: {frequent_horsepower}")

the median horsepower: 149.0
the most frequent horsepower: 152.0


In [5]:
car_table["horsepower"].median()

np.float64(149.0)

In [66]:
X = car_table.loc[car_table["origin"] == "Asia", ["vehicle_weight", "model_year"]].head(7).to_numpy()
XTX = X.T @ X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [68]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [69]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [70]:
w = XTX_inv @ X.T @ y
w

array([0.01386421, 0.5049067 ])

In [71]:
w.sum()

np.float64(0.5187709081074016)